### ISSUE TITLE
Feature request roadmap

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#70]
Yo, I centralize all my incomplete feature request in this issue (from https://github.com/Jeffser/Alpaca/issues/48 and https://github.com/Jeffser/Alpaca/issues/53), this will be more readable :+1: 

- [x] add a system prompt option in the settings
- [x] remove time and date on chat bubble and change the text color of the models name more grey (like subtitle)
- [x] add the default model option in the settings
- [x] make chat bubble width smaller
![newdesign](https://github.com/Jeffser/Alpaca/assets/102870297/492016c0-553b-4025-9d0d-964500da0910)
- [x] add a welcome page for new chat
![welcome](https://github.com/Jeffser/Alpaca/assets/102870297/5b9d8cdb-bbd7-4d0e-af34-11aabff1faa4)

- [x] Remove subtitle in setting>general, they bring nothing
- [x] Make the used model name under the answer unselectionnable (this word doesn't exist hahaha)

Thank you :heart:

**Comment by Jeffser** [comment]
I'm starting a new semester in uni, just give me some time

**Comment by loulou64490** [comment]
> I'm starting a new semester in uni, just give me some time

Okay, good luck bro

**Comment by topiga** [comment]
That would be a great feature

**Comment by loulou64490** [comment]
@Jeffser :eyes:

**Comment by Jeffser** [comment]
ALRIGHT I'M DOING IT
Just give me a couple of days

**Comment by loulou64490** [comment]
HAHAHA love you bro

**Comment by olumolu** [comment]
This should be closed and i think same thing can be prepared again as the app is no longer same when this feature request posted.
I think @loulou64490 will make another with new app and stuff are already implemented which no longered needed to be mentioned.

**Comment by loulou64490** [comment]
> This should be closed and i think same thing can be prepared again as the app is no longer same when this feature request posted.
> I think @loulou64490 will make another with new app and stuff are already implemented which no longered needed to be mentioned.

all unchecked queries are still currently valid

**Comment by CodingKoalaGeneral** [comment]
haha i agree with the welcome screen but the alpaca should look more happy :)

**Comment by olumolu** [comment]
You need svg

**Comment by Jeffser** [comment]
Hi, I changed the way user messages are rendered

[Screencast From 2024-10-15 11-28-10.webm](https://github.com/user-attachments/assets/d2526a32-d4cc-400d-99bf-57d1427c5ac7)

https://github.com/Jeffser/Alpaca/commit/0a7f7e5ac21fcf2953897f6ee15a7103ad5aa72f

**Comment by Jeffser** [comment]
So I may or may not have forgotten about this issue, I changed the footer so now it's dimmer :)

![image](https://github.com/user-attachments/assets/c3f7029f-24e0-4feb-9ca3-7389ebf9694c)

https://github.com/Jeffser/Alpaca/commit/05563574f1dec1a3da9f0eeb9bb848d8ac3d2e52

**Comment by Jeffser** [comment]
yeah lol

**Comment by Jeffser** [comment]
I also mentioned this in a different issue but I redesigned the messages and added the edit button to bot messages

![image](https://github.com/user-attachments/assets/cabab2b7-95ea-4961-9b41-4bf7a616a82d)

**Comment by Jeffser** [comment]
I think we can finally close this issue right?

**Comment by loulou64490** [comment]
amazing

**Comment by Jeffser** [comment]
btw in case you were wondering, yes you can attach documents to a system message too

**Comment by olumolu** [comment]
> I also mentioned this in a different issue but I redesigned the messages and added the edit button to bot messages
> 
> ![image](https://private-user-images.githubusercontent.com/69224322/396276916-cabab2b7-95ea-4961-9b41-4bf7a616a82d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MTk5ODIsIm5iZiI6MTczNDQxOTY4MiwicGF0aCI6Ii82OTIyNDMyMi8zOTYyNzY5MTYtY2FiYWIyYjctOTVlYS00OTYxLTliNDEtNGJmN2E2MTZhODJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MzE4N2JiZjk2ZmZiN2UyMTFmYzdmYjhiZmI5YmRkOGRlNDQ2ODgzMzRmOGI2MzY0OTc2ZjAyZTZjZDQ2NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N6POTnLsMZOBll7fAKkpwpRPFxW2P6QCb0pNcTJJr38)

Will it able to install softwares also and run commands on system

**Comment by Jeffser** [comment]
> Will it able to install softwares also and run commands on system

Well the integrated terminal can run pretty much whatever if you install Alpaca as a system app (Arch Linux package)

But I added a certain check for Flatpak, if you give it enough permissions it can do pretty much whatever, the only limitation is that it can't actually run sudo so it changes it for pkexec, if you don't have that command stuff that requires root won't run.

if you want to test it use this command

```bash
flatpak override --talk-name=org.freedesktop.Flatpak com.jeffser.Alpaca
```

**Comment by Jeffser** [comment]
that's the same permission that makes possible terminal emulators like Konsole on Flatpak

**Comment by olumolu** [comment]
> > Will it able to install softwares also and run commands on system
> 
> Well the integrated terminal can run pretty much whatever if you install Alpaca as a system app (Arch Linux package)
> 
> But I added a certain check for Flatpak, if you give it enough permissions it can do pretty much whatever, the only limitation is that it can't actually run sudo so it changes it for pkexec, if you don't have that command stuff that requires root won't run.
> 
> if you want to test it use this command
> 
> ```shell
> flatpak override --talk-name=org.freedesktop.Flatpak com.jeffser.Alpaca
> ```

If you dont have sudo you can run many things mainly running stuff with docker or similar like thst though podman can be used... I hope it does not run rm -rf /😅

**Comment by Jeffser** [comment]
yeah but it does have pkexec though, is this thingy in case you didn't know

![image](https://github.com/user-attachments/assets/d0853715-0a56-461a-bdfa-f5e317ad43b3)

So it can actually get root privileges, pretty dangerous if you run it outside the sandbox though hahaha

**Comment by olumolu** [comment]
> yeah but it does have pkexec though, is this thingy in case you didn't know
> 
> ![image](https://private-user-images.githubusercontent.com/69224322/396398929-d0853715-0a56-461a-bdfa-f5e317ad43b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjE1NzQsIm5iZiI6MTczNDQyMTI3NCwicGF0aCI6Ii82OTIyNDMyMi8zOTYzOTg5MjktZDA4NTM3MTUtMGE1Ni00NjFhLWJkZmEtZjVlMzE3YWQ0M2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3NDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZDk2ZTRkNjY2NzE0Yjc2OGRlYmFmMmJhZDcwY2RlZDM2M2I1NzAwNzU0ZjY4NzYyMjhiYmVmM2JkODkwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5XhzNyftgjkyVdAAlx8bDrhUehxc3EOs4Lmd_dhBL08)
> 
> So it can actually get root privileges, pretty dangerous if you run it outside the sandbox though hahaha

I was thinking if you can hard code some commends which cannot be run directly from that app whether you are in a sandboxed or non-snadboxed env you can't run stuff like touching root area or installing application outside of your system repos and also should not be allowed to touch the areas like firewall... And some other areas...
